# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('fso-channel-example', ['fso'])
    obj.source = 'fso-channel-example.cc'

    obj = bld.create_ns3_program('fso-irradiance-curve', ['fso'])
    obj.source = 'fso-irradiance-curve.cc'

